<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.0.2 (Python 3.11.2 on darwin)" generated="20230601 07:53:13.886" rpa="false" schemaversion="3">
<suite id="s1" name="Loggin" source="/Users/maravallejo/Documents/AUTOMATIZACION/Netflix_RobotFramework/Netflix/specs/loggin.robot">
<test id="s1-t1" name=" Given I am in Netflix page" line="8">
<status status="FAIL" starttime="20230601 07:53:14.157" endtime="20230601 07:53:14.159">Test contains no keywords.</status>
</test>
<test id="s1-t2" name=" When I start session" line="9">
<status status="FAIL" starttime="20230601 07:53:14.160" endtime="20230601 07:53:14.161">Test contains no keywords.</status>
</test>
<test id="s1-t3" name=" Then the user logs in" line="10">
<status status="FAIL" starttime="20230601 07:53:14.162" endtime="20230601 07:53:14.163">Test contains no keywords.</status>
</test>
<status status="FAIL" starttime="20230601 07:53:13.888" endtime="20230601 07:53:14.164"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="3" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="3" skip="0" id="s1" name="Loggin">Loggin</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20230601 07:53:14.152" level="ERROR">Error in file '/Users/maravallejo/Documents/AUTOMATIZACION/Netflix_RobotFramework/Netflix/stepdefinitions/loggin-sd.robot' on line 2: Resource file '../../Netflix/pagesobjects/loggin-page.robot' does not exist.</msg>
</errors>
</robot>
